import React from "react"
import styled from "styled-components"
import Header from "../components/Header"
import Footer from "../components/Footer"

const Container = styled.div`
  display: flex;
  flex-direction: column;
  align-items: center;
  width: 100%;
  min-height: 100vh;
  background: #101010;
  color: #ffffff;

  .terms_body {
    margin-top: 162px;
    margin-bottom: 186px;
    width: 100%;
    max-width: 1200px;
    @media (max-width: 767px) {
      margin-top: 60px;
      margin-bottom: 60px;
      max-width: unset;
      padding-left: 20px;
      padding-right: 20px;
    }

    .title {
      max-width: 1200px;
      font-family: Anton;
      font-style: normal;
      font-weight: normal;
      font-size: 60px;
      line-height: 90px;
      margin-bottom: 40px;
    }

    .subtitle {
      font-family: Poppins;
      font-style: normal;
      font-weight: 800;
      font-size: 24px;
      line-height: 32px;
      @media (max-width: 767px) {
        font-size: 12px;
        line-height: 24px;
      }
    }

    .texts {
      margin-bottom: 36px;
      font-family: Poppins;
      font-style: normal;
      font-weight: normal;
      font-size: 16px;
      line-height: 32px;
      @media (max-width: 767px) {
        margin-bottom: 24px;
        font-size: 12px;
        line-height: 24px;
      }
    }
  }
`

const Terms = () => {
  return (
    <Container>
      <Header />
      <div className="terms_body">
        <div className="title">Terms &#38; Conditions</div>
        <div className="texts">Last Updated : January 16, 2022</div>
        <div className="texts">This website is operated by Good Gang Labs Pte. Ltd. Throughout the site, the term “GOOD GANG LABS”, “GG LABS”, “Beergang”, “BEERGANG”, “we”, “us”,  or “ our “ as the context may require, refer to Good Gang Labs Pte. By visiting our site and/or purchasing something from us, you engage in our Service and agree to be bound by the following terms and conditions.</div>
        <div className="texts">We reserve the right to update, change or replace any part of these Terms of services without prior written notice at any time, and it is your responsibility to periodically review these Terms of Uses to stay informed of updates. Any changes to the Terms will be in effect as of the « last updated » referenced on the site.</div>
        <div className="texts">Your continued use of this site after the last updated dates will constitute your acceptance of agreement.</div>
        <div className="texts">By visiting the website of our products merchants, in particular www.opensea.io, you also engage and agree to be bound by their terms and conditions.</div>
        <div className="texts">This website is for informational purposes and serves as a binding contract for purchasers of BEERGANG NFTs.</div>
        <div className="texts">BEERGANG is a generative collection of digital artwork (NFTs) housed and run on the Ethereum Network. Users and Collector of these NFTs are solely responsible for the safety and the management of their own private assets, which include but are not limited to Ethereum Wallets, validating all transactions and contracts generated by this website prior to and after purchases.</div>
        <div className="texts">Users certify through purchase that they understand that, as the BEERGANG smart contract runs on the Ethereum network and is bound by their system and terms, there is no ability to undo, reverse, or restore any transactions.</div>
        <div className="texts">Any connected services included this website are provided “as is” and “as available” without any warranty of any kind. Use of this website constitutes your agreement that you are accepting sole responsibility for any and all transactions involving BEERGANG digital collectibles.</div>
        <div className="texts">By agreeing to these Terms of Service, you represent that you are at least the age of majority in your state or province of residence.</div>
        <div className="texts">You may not use our products and/or services for any illegal or unauthorized purpose nor may you, in the use of the Service, violate any laws in your jurisdiction (including but not limited to copyright laws).</div>
        <div className="subtitle">Ownership</div>
        <div className="texts">When you purchase your BEERGANG NFT, You Own the NFT: the ownership is transferred to you on the Ethereum blockchain for that individual piece of Art combination of traits and number. Ownership of the NFT is ruled by the smart contract and the Ethereum Network terms. We, BEERGANG, have no ability to alter, freeze, seize or modify the ownership of any BEERGANG NFT.</div>
        <div className="subtitle">Personal Usage</div>
        <div className="texts">Subject to your continued acceptance with these terms, BEERGANG allows you a worldwide, royalty-free licence to use, copy and display the purchased Art, along with any derivative artwork or extensions that you could create or use, limited by the following purposes : (i) for your own personal, non commercial use; (ii) as part of a marketplace that allows the purchase and sales of you BEERGANG / NFT, as long as the marketplace cryptographically verifies that you are the owner, to ensure that only the actual owner have the right to display the Art; or (iii) as part of a third party website or application that permits the inclusion, involvement or participation of your BEERGANG, provided that the website or the application cryptographically verifies each BEERGANG owner’s right to display the Art for their BEERGANG, to ensure that only the actual owner can display the Art, and provided that the Art is no longer visible once the actual owner of the BEERGANG leave the website or application.</div>
        <div className="subtitle">Commercial Usage</div>
        <div className="texts">Subject to actual owner of BEERGANG NFTs continued compliance with these Terms, BEERGANG grants you an unlimited, worldwide licence to use, copy and display the purchased Art for the purpose of creating derivative works based upon the Art (“COMMERCIAL USAGE”). Examples of specified Commercial Use would be the use of the Art to produce and sell physical merchandise products (T-Shirt, Posters, etc.) displaying copie of the purchased Art. Please be aware that nothing in this section will be deemed to restrict you from (i) owning or operating a marketplace that permits the use and sale of BEERGANG generally, provided that the marketplace cryptographically verifies each BEERGANG owner’s right to display the Art of their BEERGANG to ensure that only the actual owner can display the Art; (ii) owning or operating a third party website or application that permits the inclusion, involvement, or participation of BEERGANG generally, provided that the third party website or application cryptographically verifies each BEERGANG owner’s rights to display the Art for their BEERGANG to ensure that only the actual owner can display the Art, and provided that the Art is no longer visible once the owner of the Purchased BEERGANG leaves the website/application; or (iii) earning revenue from any of the foregoing.</div>
        <div className="texts">Further, BEERGANG reserves the right to use ANY character, including: print or digital advertising, or any purely creative media (including short film, anime, etc.) in support of the BEERGANG community and message.</div>
        <div className="texts">However, you cannot use the artwork in connection with images of hatred, violence or any other inappropriate behavior. The License granted in above only applies to the extent that you continue to own the relevant NFT. If at any time you trade, donate, giveaway, transfer or otherwise dispose of your NFT for any reason, the license granted above will immediately expire, without notice, and you will have no further right in or to the artwork of this NFT.</div>
        <div className="subtitle">BEERGANG IP</div>
        <div className="texts">Other than the rights to the Art, nothing gives you any rights to any other trademarks or other intellectual property rights belonging to BEERGANG including, without limitation BEERGANG, and the associated logos. All of these rights are expressly reserved in the name of BEERGANG.</div>
        <div className="subtitle">Feedback</div>
        <div className="texts">You can submit comments, bug reports, ideas about the site or the project. By submitting any feedback, you agree that we are free to use them in any way we choose without additional compensation to you and you hereby grant us a perpetual, irrevocable, nonexclusive worldwide licence to incorporate and use the feedback for any purpose.</div>
      </div>
      <Footer />
    </Container>
  )
}

export default Terms
